mysql:
  host: 127.0.0.1
  port: 3306
  config: "charset=utf8mb4&parseTime=True&loc=Local"
  db: gvb_db
  user: root
  password: root
  log_level: dev
upload:
  size: 2
  path: uploads/file
logger:
  level: info
  prefix: '[gvb]'
  director: log
  show_line: true
  log_in_console: true
system:
  host: 0.0.0.0
  port: 8080
  env: release
site_info:
  created_at: ""
  bei_an: ""
  title: "666"
  qq_image: ""
  version: ""
  email: ""
  wechat_image: ""
  name: ""
  job: ""
  addr: ""
  slogan: ""
  slogan_en: ""
  web: ""
  bilibili_url: ""
  gitee_url: ""
  github_url: ""
qq:
  app_id: xxx
  key: xxx
  redirect: http://blog.fengfengzhidao.com/login?flag=qq
qi_niu:
  enable: true
  access_key: hlumV37M3ruNNQLSomg1ofp0lJm0G8hHizxo1z_U
  secret_key: rWaaEyXJ8YAE0KLAGax_p_ggk0LQT4IGsl99xCC5
  bucket: gvb-rick
  cdn: s6u7lc6ve.hn-bkt.clouddn.com/
  zone: z2
  prefix: gvb
  size: 6
email:
  host: smtp.qq.com
  port: 465
  user: 1216820014@qq.com
  password: zh301255
  default_from_email: 高瑞克
  use_ssl: true
  user_tls: false
jwy:
  secret: xxxx
  expires: 20
  issuer: "1234"
redis:
  ip: "127.0.0.1"
  port: 6379
  password: 000000
  pool_size: 100